### ISSUE TITLE
请问如何添加过滤日志

### ISSUE THREAD

**Issue by liyiqqq** [1248289414/luci-app-adbyby#1]
我尝试使用PuTTY连接路由器，手动执行下面的代码，是可以查看到日志的
/usr/share/adbyby/adbyby &> /tmp/log/adbyby.log &

我原以为在/usr/share/adbyby/startadbb 就是路由管理界面上启动时的运行脚本
将上面的脚本添加之后，貌似并没有按脚本内容启动

之后查包代码，找到/etc/init.d/adbyby 界面上的启用停用，应该是执行的里面的start 和stop吧
请问 我应该如何修改才能输出日志文件呢？

**Comment by 1248289414** [comment]
将init.d脚本里面的
`service_start /usr/share/adbyby/adbyby`
改成
`/usr/share/adbyby/adbyby > /tmp/log/adbyby.log &`

**Comment by liyiqqq** [comment]
好的，已经能能输出日志文件了，谢谢
